### ISSUE TITLE
java.lang.SecurityException: Requires VIBRATE permission

### ISSUE THREAD

**Issue by sagrma** [aceforth/nativescript-vibrate#121]
sorry for my ignorance, I have just started nativescript
my issue is i installed the vibrate NativeScript plugin on playground but when my app in preview is calling 
the vibrator.vibrate(2000);

i get the following error

`[Galaxy Note9]: An uncaught Exception occurred on "main" thread.
Calling js method onClick failed
Error: java.lang.SecurityException: Requires VIBRATE permission

StackTrace:
Vibrate.vibrate(file:///data/data/org.nativescript.preview/files/app/nativescript-vibrate/vibrate.js:18:43)
at test(file:///data/data/org.nativescript.preview/files/app/home/home-page.js:292:14)
at exports.onButtonTap3(file:///data/data/org.nativescript.preview/files/app/home/home-page.js:470:3)
at Observable.notify(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/data/observable/observable.js:110:23)
at Observable._emit(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/data/observable/observable.js:127:18)
at ClickListenerImpl.onClick(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/button/button.js:29:23)
at com.tns.Runtime.callJSMethodNative(Native Method)
at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1286)
at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173)
at com.tns.Runtime.callJSMethod(Runtime.java:1160)
at com.tns.Runtime.callJSMethod(Runtime.java:1138)
at com.tns.Runtime.callJSMethod(Runtime.java:1134)
at com.tns.gen.java.lang.Object_button_22_32_ClickListenerImpl.onClick(Object_button_22_32_ClickListenerImpl.java:18)
at android.view.View.performClick(View.java:7333)
at android.widget.TextView.performClick(TextView.java:14160)
at android.view.View.performClickInternal(View.java:7299)
at android.view.View.access$3200(View.java:846)
at android.view.View$PerformClick.run(View.java:27773)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:6990)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
Caused by: java.lang.SecurityException: Requires VIBRATE permission
at android.os.Parcel.createException(Parcel.java:1966)
at android.os.Parcel.readException(Parcel.java:1934)
at android.os.Parcel.readException(Parcel.java:1884)
at android.os.IVibratorService$Stub$Proxy.vibrate(IVibratorService.java:304)
at android.os.SystemVibrator.vibrate(SystemVibrator.java:83)
at android.os.Vibrator.vibrate(Vibrator.java:265)
at android.os.Vibrator.vibrate(Vibrator.java:184)
at android.os.Vibrator.vibrate(Vibrator.java:163)
... 19 more
Caused by: android.os.RemoteException: Remote stack trace:
at com.android.server.VibratorService.vibrate(VibratorService.java:1131)
at android.os.IVibratorService$Stub.onTransact(IVibratorService.java:81)
at android.os.Binder.execTransact(Binder.java:739)`

**Comment by sagrma** [comment]
the issue is not when i build using cli as i have added the permission in file manually 
but in nativescript preview

**Comment by juliomrqz** [comment]
Please, use the [issue template](.github/ISSUE_TEMPLATE/bug_report.md) in order to review your issue. Thanks.
